### ISSUE TITLE
lunar eclipse 

### ISSUE THREAD

**Issue by hasanelfalakiy** [gmiller123456/FiveMillenniumCanonOfSolarEclipses-Besselian-Elements#4]
This is for a solar eclipse, then where is the lunar eclipse?

**Comment by gmiller123456** [comment]
I'm not aware of any source.  I believe most people compute lunar eclipses directly since the circumstances are the same for everyone that can view it.

**Comment by hasanelfalakiy** [comment]
> I'm not aware of any source.  I believe most people compute lunar eclipses directly since the circumstances are the same for everyone that can view it.

ok,,, do you know how to calculate the position of the sun and moon with jpl de4xx? i want to calculate and program it for my android application, but i still don't understand

**Comment by gmiller123456** [comment]
Here is an article on using JPL DE: https://www.celestialprogramming.com/jpl-ephemeris-format/jpl-ephemeris-format.html

**Comment by hasanelfalakiy** [comment]
> Here is an article on using JPL DE: https://www.celestialprogramming.com/jpl-ephemeris-format/jpl-ephemeris-format.html

okay thanks

**Comment by hasanelfalakiy** [comment]
> Here is an article on using JPL DE: https://www.celestialprogramming.com/jpl-ephemeris-format/jpl-ephemeris-format.html

I'm starting to understand the file structure, but the example on the website shows the output data as Cartesian coordinates with km units, then...then how to transform to spherical coordinates, ecliptic and others such as LBR, ascensio recta, declination?

**Comment by hasanelfalakiy** [comment]
> > Here is an article on using JPL DE: https://www.celestialprogramming.com/jpl-ephemeris-format/jpl-ephemeris-format.html
> 
> I'm starting to understand the file structure, but the example on the website shows the output data as Cartesian coordinates with km units, then...then how to transform to spherical coordinates, ecliptic and others such as LBR, ascensio recta, declination?

@gmiller123456 please anwer sir

**Comment by hasanelfalakiy** [comment]
> Here is an article on using JPL DE: https://www.celestialprogramming.com/jpl-ephemeris-format/jpl-ephemeris-format.html

Dear gmiller, does your java code support reading DE440? https://github.com/gmiller123456/jpl-development-ephemeris/tree/master/Binary/Java

**Comment by gmiller123456** [comment]
Yes

**Comment by hasanelfalakiy** [comment]
> Yes

okay, then from ICRF/ICRS framework to true equinox of date or mean equinox of date how to convert it? do you know the formula?

**Comment by gmiller123456** [comment]
I have some code that goes through the full reduction process (precession, nutation, aberration, parallax, etc.).  Been meaning to write an article on it, but haven't gotten to it yet.  Other sources are Meeus' Astromical Algorithms, or the Explanatory Supplement to the Astronomical Almanac.

Here is code that does most of the reduction process:
https://github.com/gmiller123456/vsop87-multilang/blob/master/Languages/JavaScript/CelestialProgrammingReduce.js

And here is a repository that has it broken down into different levels, but no explanation:
https://github.com/gmiller123456/ReductionWalkthrough

**Comment by hasanelfalakiy** [comment]
> I have some code that goes through the full reduction process (precession, nutation, aberration, parallax, etc.).  Been meaning to write an article on it, but haven't gotten to it yet.  Other sources are Meeus' Astromical Algorithms, or the Explanatory Supplement to the Astronomical Almanac.
> 
> Here is code that does most of the reduction process:
> https://github.com/gmiller123456/vsop87-multilang/blob/master/Languages/JavaScript/CelestialProgrammingReduce.js
> 
> And here is a repository that has it broken down into different levels, but no explanation:
> https://github.com/gmiller123456/ReductionWalkthrough


Thank you sir, I will be happy to wait for the explanation in your article later, if the article is finished please let me know, okay? I also have the book but I'm still confused about understanding it ,I just finished the VSOP87D and ELPMPP02 model code here, if you don't mind, you can check if the reduction method is the same
 https://github.com/hasanelfalakiy/lib-vsop87d-elpmpp02/tree/main/lib/src/main/kotlin/com/andihasan7/lib/vsop87d/elpmpp02

**Comment by hasanelfalakiy** [comment]
> I have some code that goes through the full reduction process (precession, nutation, aberration, parallax, etc.).  Been meaning to write an article on it, but haven't gotten to it yet.  Other sources are Meeus' Astromical Algorithms, or the Explanatory Supplement to the Astronomical Almanac.
> 
> Here is code that does most of the reduction process:
> https://github.com/gmiller123456/vsop87-multilang/blob/master/Languages/JavaScript/CelestialProgrammingReduce.js
> 
> And here is a repository that has it broken down into different levels, but no explanation:
> https://github.com/gmiller123456/ReductionWalkthrough


sir, Is your article explaining how to reduce ephemeris coordinates finished?

after reading, I think reducing data from JPL DE is the same as VSOP87D & ELP/MPP02, right? although the reference system & celestial frame are from ICRS & ICRF

then what I want to ask, in the explanatory supplement book, 3rd edition, it is written there that ICRF/ICRS is aligned with the J2000 mean, with a difference of 0.002 arc seconds, so ICRS/ICRF can also be considered mean J2000?

**Comment by hasanelfalakiy** [comment]
> I have some code that goes through the full reduction process (precession, nutation, aberration, parallax, etc.).  Been meaning to write an article on it, but haven't gotten to it yet.  Other sources are Meeus' Astromical Algorithms, or the Explanatory Supplement to the Astronomical Almanac.
> 
> Here is code that does most of the reduction process:
> https://github.com/gmiller123456/vsop87-multilang/blob/master/Languages/JavaScript/CelestialProgrammingReduce.js
> 
> And here is a repository that has it broken down into different levels, but no explanation:
> https://github.com/gmiller123456/ReductionWalkthrough


I have successfully managed and read DE, I have another question, how do I know if the binary format DE file is damaged or corrupt? because when my application reads a damaged/corrupted DE binary file my application crashes/force closes, please answer sir

**Comment by gmiller123456** [comment]
Many people use the binary DE files OK, so it's unlikely they are corrupt.
